# Build the Go Binary.
FROM golang:1.14.4 as build_sales-api
ENV CGO_ENABLED 0

# Create a location in the container for the source code. Using the
# default GOPATH location.
RUN mkdir -p /service

# Copy the source code into the container.
WORKDIR /service
COPY . .

# Build the admin tool so we can have it in the container. This should not change
# often so do this first.
WORKDIR /service/app/sales-api/
RUN go build -ldflags "-X main.build=prod"

# Run the Go Binary in Alpine.
FROM alpine:3.7
COPY --from=build_sales-api /service/private.pem /app/private.pem
COPY --from=build_sales-api /service/app/sales-api/sales-api /app/main
WORKDIR /app
CMD ["/app/main"]
